config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks
  post "tasks/:id/toggle", to: "tasks#toggle"
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :integer          not null, primary key
#  completed   :boolean
#  description :string(200)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Task < ApplicationRecord
  validates_presence_of :description
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def create
    @task = Task.new(task_params)
    @tasks = Task.all

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def task_params
    params.require(:task).permit(:description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def toggle
    @task = Task.find(params[:id])
    @task.update(completed: params[:completed])
    render json: { message: "Success" }
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_url, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "Task was successfully deleted."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Now - Chetan Mittal Dev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

<header>
  <nav class="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 items-center justify-between">
      <figure class="flex flex-shrink-0 items-center space-x-1">
        <img
          alt="Chetan Mittal - Senior Polyglot Web Developer"
          class="h-8 w-auto"
          src="<%= image_path('logo-cmd.jpeg') %>"
          height="32"
          width="32"
        />
        <figcaption><b>Chetan Mittal</b></figcaption>
      </figure>
      <ul class="flex space-x-4">
        <li>
          <a href="https://www.chetanmittaldev.com/" class="text-base font-bold underline hover:text-blue-600">
            Home
          </a>
        </li>
        <li>
          <a href="https://www.chetanmittaldev.com/consulting/" class="text-base font-bold underline hover:text-blue-600">
            Consulting
          </a>
        </li>
        <li>
          <a href="https://www.chetanmittaldev.com/training/" class="text-base font-bold underline hover:text-blue-600">
            Training
          </a>
        </li>
        <li>
          <a href="https://www.chetanmittaldev.com/contact/" class="text-base font-bold underline hover:text-blue-600">
            Contact
          </a>
        </li>
        <li>
          <a href="https://blog.chetanmittaldev.com/" class="text-base font-bold underline hover:text-blue-600" target="_blank">
            Blog
          </a>
        </li>
        <li>
          <a href="https://now.chetanmittaldev.com/" class="text-base font-bold" aria-current="page" title="What I am working on now?!!">
            Now
          </a>
        </li>
      </ul>
    </div>
  </nav>
</header>

    <div class="py-10">
      <main class="container mx-auto">
        <div class="mx-auto max-w-4xl px-4 sm:px-6 lg:py-8 lg:px-8">
          <%= yield %>
        </div>
      </main>
    </div>

    <footer class="mx-auto mb-6 max-w-4xl p-4 sm:px-6 lg:px-8 w-2/3 text-xs">
      <div>
        <p class="text-slate-600">&copy; <%= Date.today.year %> <a href="https://www.chetanmittaldev.com" target="_blank" class="text-blue-600 hover:text-sky-600">Chetan Mittal</a>. All rights reserved. </p>
        <p class="text-slate-600">Powered by - Rails 7, HotwireJS, TailwindCSS, and PostgreSQL. <br/> Deployed on Fly.io FREE Tier.</p>
        <p class="text-slate-600">
        <a href="https://github.com/chetanmittaldev/todotiger" target="_blank">
          <img src="https://img.icons8.com/material-sharp/24/000000/github.png" />
        </a>
        </p>
      </div>
    </footer>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "mb-7") do |form| %>
<% if task.errors.any? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2>
      <%= pluralize(task.errors.count, "error") %>
      prohibited this task from being saved:
    </h2>
    <ul>
    <% task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="mb-5">
    <%= form.text_field :description, placeholder: "Add new task", class: "inline-block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-2/3" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="block">
  <%= form_with(model: task, class:"text-lg inline-block my-3") do |form| %>
    <%= form.check_box :completed,
        data: {
          id: task.id,
          action: "tasks#toggle"
        }, 
        class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500",
        disabled: current_user ? false : true
    %>
        <%= task.description %>
    <% end %>
  <% if current_user %>
    <%= link_to "Edit", edit_task_path(task), class: "btn bg-gray-100" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete", task_path(task),
          method: :delete,
          data: { action: "tasks#delete" },
          class: "btn bg-red-100" 
      %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <div id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Never Mind", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </div>
</div>

app/views/tasks/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<h1 class="font-bold text-2xl">
  What I am working on right now!
</h1>

<% unless current_user %>
  <span><a href="<%= new_user_session_path %>" class="text-blue-600 hover:text-sky-600">[Login]</a></span>
<% else %>
  <span><a href="<%= destroy_user_session_path %>" class="text-blue-600 visited:text-purple-600" data-turbo-method="delete">Logout</a></span>
<% end %>

<% if current_user %>
  <div class="mt-4">
    <%= render "form", task: @task %>
  </div>
<% else %>
  <div class="mt-4" />
<% end %>

<div id="tasks">
  <h1 class="font-bold text-lg mb-3">Todos</h1>
  <div class="px-5" data-controller="tasks">
    <%= render @tasks %>
  </div>
</div>

app/views/tasks/show.html.erb
<!-- This is just a test - DELETE IT -->